# .github/workflows/task3.yml

name: ECR CI/CD

on:
    push:
        branches: ["main"]


jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Building the image
              run: docker compose up --build -d

            - name: Health Check
              run: |
                echo "Waiting for service to be ready..."
                sleep 15
                curl -f http://localhost:80 || exit 1
            
            - name: Stop services
              run: docker compose down
              if: always()

    scan:
        name: Run Trivy vulnerability scanner 
        needs: [build-and-test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build image for scanning
              run: docker compose build
            
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                    image-ref: 'docker-cicd_utility:latest'  # Correct naming
                    format: 'table'
                    exit-code: '1'
                    severity: 'CRITICAL,HIGH'


        
    # push:
    #     name: pushing
    #     needs: [build, test, scan]
    #     steps:
    #         - name: Login to Amazon ECR
    #           id: login-ecr
    #           uses: aws-actions/amazon-ecr-login@v2
