# .github/workflows/task3.yml

name: ECR CI/CD

on:
    push:
        branches: ["main"]


jobs:

    build-test-scan-push:
        name: Run Trivy vulnerability scanner 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build image for scanning
              run: docker compose build
            
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                    image-ref: 'utility:latest'  # Correct naming
                    format: 'table'
                    exit-code: '1'
                    severity: 'CRITICAL,HIGH'

            - name: Test - Health Check 
              run: |
                echo "Waiting for service to be ready..."
                sleep 15
                curl -f http://localhost:80 || exit 1
            
            - name: Stop services
              run: docker compose down
              if: always()


            - name: Setup AWS ECR Details
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Push docker image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  
                ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
              run: |
                docker tag utility:latest $ECR_REGISTRY/$ECR_REPOSITORY/utility:latest
                docker push $ECR_REGISTRY/$ECR_REPOSITORY/utility:latest
